### ISSUE TITLE
I2P plus console not appearing anymore after update

### ISSUE THREAD

**Issue by AntiWorkIncel** [I2PPlus/i2pplus#1282]
I just updated I2P and then it's only appearing the default console now.

**Comment by vituperative** [comment]
OK, it sounds like you updated to vanilla I2P. There are a few things you can do to prevent this happening, and to update to I2P+:
* Download the latest i2pupdate.zip file from http://skank.i2p/i2pupdate.zip or https://i2pplus.github.io/i2pupdate.zip and copy it to your i2p application folder. Then restart your router. You should be back on I2P+.
* Once you're back on I2P+, ensure you have Unsigned development updates enabled on http://127.0.0.1:7657/configupdate .. you can leave the default URL as is for release updates, or use the alternative indicated /dev/ update URL for a more frequent update cycle.
* Configure the Update Policy to Notify Only on http://127.0.0.1:7657/configupdate so you're informed when a  new update is available and can install it at your convenience.
* When an update presents itself in the sidebar, make sure it indicates an I2P+ update to avoid reverting back to vanilla, though this should be fixed in the latest update so only I2P+ updates are presented.

**Comment by AntiWorkIncel** [comment]
> OK, it sounds like you updated to vanilla I2P. There are a few things you can do to prevent this happening, and to update to I2P+:
> 
> * Download the latest i2pupdate.zip file from http://skank.i2p/i2pupdate.zip or https://i2pplus.github.io/i2pupdate.zip and copy it to your i2p application folder. Then restart your router. You should be back on I2P+.
> * Once you're back on I2P+, ensure you have Unsigned development updates enabled on http://127.0.0.1:7657/configupdate .. you can leave the default URL as is for release updates, or use the alternative indicated /dev/ update URL for a more frequent update cycle.
> * Configure the Update Policy to Notify Only on http://127.0.0.1:7657/configupdate so you're informed when a  new update is available and can install it at your convenience.
> * When an update presents itself in the sidebar, make sure it indicates an I2P+ update to avoid reverting back to vanilla, though this should be fixed in the latest update so only I2P+ updates are presented.

That worked, but the UI got kinda broken. How to fix this?
![Captura de tela_2024-10-26_04-28-28](https://github.com/user-attachments/assets/53ca5bca-6935-4ce9-89b7-feafc781aa1c)

**Comment by AntiWorkIncel** [comment]
Nvm. I just had to restart it a second time and now it's ok.
